
# enables deriving the term from the path. Uses a rudimentary base_path + array index
# overrides the actual term setting below if set
derive_term = true
# all other paths start here
base_path = "Dialogue"
# everything below directly maps to poe config
term = "Index"
definition = "Text"
context = "Name"
term_plural = ""
reference = ""
comment = ""
